import { NextResponse } from "next/server";

interface FlightRoute {
  id: string;
  callsign: string;
  origin: string;
  originLat: number;
  originLon: number;
  destination: string;
  destLat: number;
  destLon: number;
  type: "military" | "commercial" | "cargo" | "surveillance";
  altitude: number; // typical cruise altitude in ft
  speed: number; // typical cruise speed in knots
  active: boolean;
  progress: number; // 0-1 current position along route
}

// Major airport / military base coordinates
const LOCATIONS = [
  // US Military
  { code: "DOV", name: "Dover AFB", lat: 39.13, lon: -75.47, type: "military" },
  { code: "RMS", name: "Ramstein AB", lat: 49.44, lon: 7.60, type: "military" },
  { code: "OKO", name: "Yokota AB", lat: 35.75, lon: 139.35, type: "military" },
  { code: "LTS", name: "Altus AFB", lat: 34.67, lon: -99.27, type: "military" },
  { code: "LWR", name: "Lajes Field", lat: 38.76, lon: -27.09, type: "military" },
  { code: "Souda", name: "Souda Bay NSA", lat: 35.53, lon: 24.15, type: "military" },
  { code: "AlUdeid", name: "Al Udeid AB", lat: 25.12, lon: 51.32, type: "military" },
  { code: "AlDhafra", name: "Al Dhafra AB", lat: 24.25, lon: 54.55, type: "military" },
  { code: "Incirlik", name: "Incirlik AB", lat: 37.00, lon: 35.43, type: "military" },
  { code: "Spang", name: "Spangdahlem AB", lat: 49.97, lon: 6.70, type: "military" },
  { code: "Aviano", name: "Aviano AB", lat: 46.03, lon: 12.60, type: "military" },
  { code: "Mildenhall", name: "RAF Mildenhall", lat: 52.36, lon: 0.48, type: "military" },
  { code: "Fairford", name: "RAF Fairford", lat: 51.68, lon: -1.79, type: "military" },
  { code: "Thule", name: "Thule AB", lat: 76.53, lon: -68.70, type: "military" },
  { code: "Andersen", name: "Andersen AFB", lat: 13.58, lon: 144.93, type: "military" },
  { code: "Kadena", name: "Kadena AB", lat: 26.36, lon: 127.77, type: "military" },
  { code: "Osan", name: "Osan AB", lat: 37.09, lon: 127.03, type: "military" },
  { code: "Hickam", name: "Hickam AFB", lat: 21.32, lon: -157.92, type: "military" },
  { code: "Diego", name: "Diego Garcia", lat: -7.31, lon: 72.41, type: "military" },
  { code: "Sigonella", name: "NAS Sigonella", lat: 37.40, lon: 14.92, type: "military" },

  // Commercial Hubs
  { code: "JFK", name: "New York JFK", lat: 40.64, lon: -73.78, type: "commercial" },
  { code: "LHR", name: "London Heathrow", lat: 51.47, lon: -0.46, type: "commercial" },
  { code: "DXB", name: "Dubai", lat: 25.25, lon: 55.36, type: "commercial" },
  { code: "HND", name: "Tokyo Haneda", lat: 35.55, lon: 139.78, type: "commercial" },
  { code: "SIN", name: "Singapore", lat: 1.36, lon: 103.99, type: "commercial" },
  { code: "FRA", name: "Frankfurt", lat: 50.04, lon: 8.57, type: "commercial" },
  { code: "CDG", name: "Paris CDG", lat: 49.01, lon: 2.55, type: "commercial" },
  { code: "AMS", name: "Amsterdam", lat: 52.31, lon: 4.77, type: "commercial" },
  { code: "LAX", name: "Los Angeles", lat: 33.94, lon: -118.41, type: "commercial" },
  { code: "SFO", name: "San Francisco", lat: 37.62, lon: -122.38, type: "commercial" },
  { code: "ORD", name: "Chicago O'Hare", lat: 41.97, lon: -87.90, type: "commercial" },
  { code: "ATL", name: "Atlanta", lat: 33.64, lon: -84.43, type: "commercial" },
  { code: "DFW", name: "Dallas/Fort Worth", lat: 32.90, lon: -97.04, type: "commercial" },
  { code: "MIA", name: "Miami", lat: 25.80, lon: -80.29, type: "commercial" },
  { code: "YYZ", name: "Toronto", lat: 43.68, lon: -79.63, type: "commercial" },
  { code: "MEX", name: "Mexico City", lat: 19.44, lon: -99.07, type: "commercial" },
  { code: "GRU", name: "São Paulo", lat: -23.44, lon: -46.47, type: "commercial" },
  { code: "BCN", name: "Barcelona", lat: 41.30, lon: 2.08, type: "commercial" },
  { code: "FCO", name: "Rome", lat: 41.80, lon: 12.25, type: "commercial" },
  { code: "IST", name: "Istanbul", lat: 41.28, lon: 28.73, type: "commercial" },
  { code: "DOH", name: "Doha", lat: 25.27, lon: 51.61, type: "commercial" },
  { code: "DEL", name: "New Delhi", lat: 28.57, lon: 77.10, type: "commercial" },
  { code: "BOM", name: "Mumbai", lat: 19.09, lon: 72.87, type: "commercial" },
  { code: "HKG", name: "Hong Kong", lat: 22.31, lon: 113.92, type: "commercial" },
  { code: "ICN", name: "Seoul", lat: 37.46, lon: 126.44, type: "commercial" },
  { code: "PVG", name: "Shanghai", lat: 31.14, lon: 121.81, type: "commercial" },
  { code: "PEK", name: "Beijing", lat: 40.08, lon: 116.58, type: "commercial" },
  { code: "BKK", name: "Bangkok", lat: 13.69, lon: 100.75, type: "commercial" },
  { code: "SYD", name: "Sydney", lat: -33.94, lon: 151.18, type: "commercial" },
  { code: "MEL", name: "Melbourne", lat: -37.67, lon: 144.85, type: "commercial" },
  { code: "AKL", name: "Auckland", lat: -37.01, lon: 174.79, type: "commercial" },
  { code: "JNB", name: "Johannesburg", lat: -26.14, lon: 28.25, type: "commercial" },
  { code: "CAI", name: "Cairo", lat: 30.12, lon: 31.41, type: "commercial" },
  { code: "TLV", name: "Tel Aviv", lat: 32.01, lon: 34.89, type: "commercial" },
  { code: "ATH", name: "Athens", lat: 37.94, lon: 23.95, type: "commercial" },
  { code: "WAW", name: "Warsaw", lat: 52.17, lon: 20.97, type: "commercial" },
  { code: "ARN", name: "Stockholm", lat: 59.65, lon: 17.93, type: "commercial" },
  { code: "OSL", name: "Oslo", lat: 60.20, lon: 11.08, type: "commercial" },
  { code: "CPH", name: "Copenhagen", lat: 55.62, lon: 12.66, type: "commercial" },
  { code: "VIE", name: "Vienna", lat: 48.11, lon: 16.57, type: "commercial" },
  { code: "ZRH", name: "Zurich", lat: 47.46, lon: 8.55, type: "commercial" },
  { code: "MUC", name: "Munich", lat: 48.35, lon: 11.79, type: "commercial" },
  { code: "MAD", name: "Madrid", lat: 40.47, lon: -3.57, type: "commercial" },
  { code: "LIS", name: "Lisbon", lat: 38.78, lon: -9.13, type: "commercial" },
  { code: "DUB", name: "Dublin", lat: 53.43, lon: -6.24, type: "commercial" },
  { code: "KEF", name: "Reykjavik", lat: 64.13, lon: -21.94, type: "commercial" },
  { code: "HEL", name: "Helsinki", lat: 60.32, lon: 24.97, type: "commercial" },
  { code: "LED", name: "St Petersburg", lat: 59.80, lon: 30.27, type: "commercial" },
  { code: "SVO", name: "Moscow", lat: 55.97, lon: 37.41, type: "commercial" },
  { code: "BAH", name: "Bahrain", lat: 26.27, lon: 50.63, type: "commercial" },
  { code: "KWI", name: "Kuwait", lat: 29.24, lon: 47.97, type: "commercial" },
  { code: "JED", name: "Jeddah", lat: 21.68, lon: 39.16, type: "commercial" },
  { code: "RUH", name: "Riyadh", lat: 24.96, lon: 46.70, type: "commercial" },
  { code: "AUH", name: "Abu Dhabi", lat: 24.43, lon: 54.65, type: "commercial" },
  { code: "KUL", name: "Kuala Lumpur", lat: 2.75, lon: 101.71, type: "commercial" },
  { code: "CGK", name: "Jakarta", lat: -6.13, lon: 106.66, type: "commercial" },
  { code: "MNL", name: "Manila", lat: 14.51, lon: 121.02, type: "commercial" },
  { code: "HAN", name: "Hanoi", lat: 21.22, lon: 105.81, type: "commercial" },
  { code: "SGN", name: "Ho Chi Minh", lat: 10.82, lon: 106.65, type: "commercial" },
  { code: "TPE", name: "Taipei", lat: 25.08, lon: 121.23, type: "commercial" },
  { code: "NRT", name: "Tokyo Narita", lat: 35.76, lon: 140.39, type: "commercial" },
  { code: "KIX", name: "Osaka Kansai", lat: 34.43, lon: 135.24, type: "commercial" },
  { code: "NGO", name: "Nagoya", lat: 35.26, lon: 136.92, type: "commercial" },
  { code: "CTS", name: "Sapporo", lat: 43.11, lon: 141.38, type: "commercial" },
  { code: "FUK", name: "Fukuoka", lat: 33.59, lon: 130.45, type: "commercial" },
  { code: "SEA", name: "Seattle", lat: 47.45, lon: -122.31, type: "commercial" },
  { code: "DEN", name: "Denver", lat: 39.86, lon: -104.67, type: "commercial" },
  { code: "PHX", name: "Phoenix", lat: 33.43, lon: -112.01, type: "commercial" },
  { code: "LAS", name: "Las Vegas", lat: 36.08, lon: -115.15, type: "commercial" },
  { code: "BOS", name: "Boston", lat: 42.36, lon: -71.01, type: "commercial" },
  { code: "PHL", name: "Philadelphia", lat: 39.87, lon: -75.24, type: "commercial" },
  { code: "DCA", name: "Washington DC", lat: 38.85, lon: -77.04, type: "commercial" },
  { code: "IAD", name: "Washington Dulles", lat: 38.95, lon: -77.45, type: "commercial" },
  { code: "YVR", name: "Vancouver", lat: 49.20, lon: -123.18, type: "commercial" },
  { code: "YUL", name: "Montreal", lat: 45.47, lon: -73.74, type: "commercial" },
  { code: "GIG", name: "Rio de Janeiro", lat: -22.81, lon: -43.25, type: "commercial" },
  { code: "EZE", name: "Buenos Aires", lat: -34.82, lon: -58.53, type: "commercial" },
  { code: "SCL", name: "Santiago", lat: -33.39, lon: -70.79, type: "commercial" },
  { code: "LIM", name: "Lima", lat: -12.02, lon: -77.11, type: "commercial" },
  { code: "BOG", name: "Bogotá", lat: 4.70, lon: -74.15, type: "commercial" },
  { code: "PTY", name: "Panama City", lat: 9.07, lon: -79.38, type: "commercial" },
  { code: "SJU", name: "San Juan", lat: 18.44, lon: -66.00, type: "commercial" },
  { code: "HAV", name: "Havana", lat: 22.99, lon: -82.41, type: "commercial" },
];

// Typical routes that are active (military + commercial)
const ROUTE_PAIRS: [string, string, "military" | "commercial" | "cargo" | "surveillance", number][] = [
  // Military routes
  ["DOV", "RMS", "military", 35000],
  ["DOV", "LWR", "military", 33000],
  ["LWR", "RMS", "military", 32000],
  ["RMS", "AlUdeid", "military", 36000],
  ["RMS", "Incirlik", "military", 34000],
  ["AlUdeid", "AlDhafra", "military", 32000],
  ["AlUdeid", "Kadena", "military", 37000],
  ["AlDhafra", "Incirlik", "military", 33000],
  ["RMS", "Fairford", "military", 31000],
  ["Fairford", "Spang", "military", 30000],
  ["Spang", "Aviano", "military", 28000],
  ["Aviano", "Incirlik", "military", 32000],
  ["Aviano", "Souda", "military", 30000],
  ["Souda", "Sigonella", "military", 27000],
  ["Sigonella", "AlUdeid", "military", 35000],
  ["Mildenhall", "RMS", "military", 31000],
  ["Mildenhall", "Fairford", "military", 29000],
  ["Mildenhall", "AlUdeid", "military", 36000],
  ["Thule", "Mildenhall", "military", 34000],
  ["OKO", "AlUdeid", "military", 38000],
  ["OKO", "Kadena", "military", 37000],
  ["Kadena", "Osan", "military", 28000],
  ["Osan", "Yokota", "military", 32000],
  ["Yokota", "Hickam", "military", 36000],
  ["Hickam", "Andersen", "military", 37000],
  ["Andersen", "AlUdeid", "military", 39000],
  ["Diego", "AlUdeid", "military", 35000],
  ["Diego", "OKO", "military", 37000],
  ["LTS", "LWR", "military", 34000],
  ["LTS", "RMS", "military", 35000],
  ["LTS", "AlUdeid", "military", 36000],

  // Commercial transatlantic
  ["JFK", "LHR", "commercial", 38000],
  ["JFK", "CDG", "commercial", 39000],
  ["JFK", "FRA", "commercial", 39000],
  ["JFK", "AMS", "commercial", 38000],
  ["JFK", "FCO", "commercial", 40000],
  ["LAX", "LHR", "commercial", 41000],
  ["LAX", "CDG", "commercial", 41000],
  ["LAX", "FRA", "commercial", 41000],
  ["SFO", "LHR", "commercial", 40000],
  ["SFO", "CDG", "commercial", 41000],
  ["SFO", "FRA", "commercial", 41000],
  ["SFO", "SIN", "commercial", 42000],
  ["SFO", "HND", "commercial", 39000],
  ["ORD", "LHR", "commercial", 38000],
  ["ORD", "FRA", "commercial", 39000],
  ["ORD", "CDG", "commercial", 39000],
  ["ATL", "LHR", "commercial", 38000],
  ["ATL", "CDG", "commercial", 39000],
  ["DFW", "LHR", "commercial", 39000],
  ["MIA", "MAD", "commercial", 37000],
  ["MIA", "BCN", "commercial", 38000],
  ["YYZ", "LHR", "commercial", 38000],
  ["YYZ", "FRA", "commercial", 39000],
  ["YYZ", "CDG", "commercial", 39000],
  ["YVR", "LHR", "commercial", 39000],
  ["YVR", "HND", "commercial", 38000],

  // Europe-Asia
  ["LHR", "DXB", "commercial", 39000],
  ["LHR", "SIN", "commercial", 40000],
  ["LHR", "HND", "commercial", 39000],
  ["LHR", "BKK", "commercial", 40000],
  ["LHR", "DEL", "commercial", 39000],
  ["LHR", "PEK", "commercial", 40000],
  ["FRA", "DXB", "commercial", 39000],
  ["FRA", "SIN", "commercial", 40000],
  ["FRA", "HND", "commercial", 39000],
  ["FRA", "BOM", "commercial", 39000],
  ["CDG", "DXB", "commercial", 39000],
  ["CDG", "HND", "commercial", 39000],
  ["CDG", "SIN", "commercial", 40000],
  ["AMS", "DXB", "commercial", 39000],
  ["AMS", "SIN", "commercial", 40000],
  ["AMS", "HND", "commercial", 39000],
  ["IST", "DXB", "commercial", 37000],
  ["IST", "SIN", "commercial", 39000],
  ["IST", "HND", "commercial", 38000],
  ["IST", "JNB", "commercial", 38000],
  ["ATH", "DXB", "commercial", 37000],
  ["WAW", "DXB", "commercial", 38000],

  // Asia-Pacific
  ["HND", "SIN", "commercial", 37000],
  ["HND", "BKK", "commercial", 37000],
  ["HND", "HKG", "commercial", 36000],
  ["HND", "ICN", "commercial", 35000],
  ["HND", "SYD", "commercial", 39000],
  ["HND", "AKL", "commercial", 39000],
  ["SIN", "HKG", "commercial", 35000],
  ["SIN", "BKK", "commercial", 35000],
  ["SIN", "SYD", "commercial", 38000],
  ["SIN", "MEL", "commercial", 38000],
  ["SIN", "DEL", "commercial", 37000],
  ["SIN", "BOM", "commercial", 36000],
  ["SIN", "DXB", "commercial", 38000],
  ["SIN", "PEK", "commercial", 37000],
  ["SIN", "PVG", "commercial", 36000],
  ["HKG", "BKK", "commercial", 34000],
  ["HKG", "PEK", "commercial", 35000],
  ["HKG", "PVG", "commercial", 34000],
  ["HKG", "SFO", "commercial", 40000],
  ["HKG", "LAX", "commercial", 40000],
  ["PEK", "DXB", "commercial", 38000],
  ["PEK", "LHR", "commercial", 40000],
  ["PEK", "FRA", "commercial", 40000],
  ["PEK", "SFO", "commercial", 41000],
  ["PVG", "LAX", "commercial", 41000],
  ["PVG", "SFO", "commercial", 41000],
  ["PVG", "DXB", "commercial", 39000],
  ["PVG", "SYD", "commercial", 39000],
  ["BKK", "DXB", "commercial", 36000],
  ["BKK", "PEK", "commercial", 36000],
  ["BKK", "HND", "commercial", 37000],
  ["ICN", "LAX", "commercial", 40000],
  ["ICN", "SFO", "commercial", 40000],
  ["ICN", "HND", "commercial", 34000],
  ["ICN", "SIN", "commercial", 37000],
  ["ICN", "BKK", "commercial", 36000],
  ["TPE", "LAX", "commercial", 40000],
  ["TPE", "SFO", "commercial", 40000],
  ["TPE", "SIN", "commercial", 36000],
  ["TPE", "HND", "commercial", 34000],
  ["NRT", "LAX", "commercial", 40000],
  ["NRT", "SFO", "commercial", 40000],
  ["NRT", "HNL", "commercial", 38000],
  ["KIX", "HNL", "commercial", 38000],
  ["KUL", "SIN", "commercial", 32000],
  ["KUL", "SYD", "commercial", 38000],
  ["KUL", "DXB", "commercial", 37000],
  ["CGK", "SIN", "commercial", 33000],
  ["MNL", "SIN", "commercial", 34000],
  ["MNL", "HKG", "commercial", 34000],
  ["HAN", "SIN", "commercial", 34000],
  ["SGN", "SIN", "commercial", 33000],

  // Middle East connections
  ["DXB", "LHR", "commercial", 39000],
  ["DXB", "JFK", "commercial", 40000],
  ["DXB", "SFO", "commercial", 41000],
  ["DXB", "SIN", "commercial", 38000],
  ["DXB", "BKK", "commercial", 37000],
  ["DXB", "HND", "commercial", 39000],
  ["DXB", "SYD", "commercial", 40000],
  ["DXB", "DEL", "commercial", 36000],
  ["DXB", "BOM", "commercial", 35000],
  ["DXB", "CAI", "commercial", 34000],
  ["DXB", "JNB", "commercial", 38000],
  ["DOH", "LHR", "commercial", 39000],
  ["DOH", "JFK", "commercial", 40000],
  ["DOH", "SIN", "commercial", 38000],
  ["DOH", "HND", "commercial", 39000],
  ["DOH", "SYD", "commercial", 40000],
  ["AUH", "LHR", "commercial", 39000],
  ["AUH", "JFK", "commercial", 40000],
  ["AUH", "SIN", "commercial", 38000],
  ["JED", "LHR", "commercial", 39000],
  ["JED", "JFK", "commercial", 40000],
  ["JED", "DXB", "commercial", 33000],
  ["KWI", "LHR", "commercial", 39000],
  ["KWI", "DXB", "commercial", 32000],
  ["BAH", "LHR", "commercial", 39000],
  ["BAH", "DXB", "commercial", 31000],
  ["TLV", "JFK", "commercial", 40000],
  ["TLV", "LHR", "commercial", 39000],
  ["TLV", "FRA", "commercial", 38000],
  ["TLV", "DXB", "commercial", 34000],
  ["CAI", "LHR", "commercial", 38000],
  ["CAI", "JFK", "commercial", 39000],
  ["CAI", "DXB", "commercial", 34000],

  // Cargo routes
  ["HKG", "ANC", "cargo", 35000],
  ["HKG", "ORD", "cargo", 38000],
  ["HKG", "DFW", "cargo", 38000],
  ["SIN", "ANC", "cargo", 37000],
  ["DXB", "LEJ", "cargo", 38000],
  ["LEJ", "ANC", "cargo", 36000],
  ["LEJ", "MEM", "cargo", 37000],
  ["LEJ", "ORD", "cargo", 37000],
  ["MEM", "NRT", "cargo", 38000],
  ["MEM", "DXB", "cargo", 38000],
  ["SDF", "DXB", "cargo", 38000],
  ["SDF", "HKG", "cargo", 39000],

  // Australia / Oceania
  ["SYD", "LAX", "commercial", 39000],
  ["SYD", "SFO", "commercial", 39000],
  ["SYD", "HND", "commercial", 39000],
  ["SYD", "SIN", "commercial", 38000],
  ["SYD", "DXB", "commercial", 40000],
  ["SYD", "LHR", "commercial", 40000],
  ["MEL", "SIN", "commercial", 38000],
  ["MEL", "DXB", "commercial", 40000],
  ["MEL", "HND", "commercial", 39000],
  ["AKL", "SIN", "commercial", 38000],
  ["AKL", "HND", "commercial", 39000],
  ["AKL", "LAX", "commercial", 39000],
  ["AKL", "SFO", "commercial", 39000],

  // South America
  ["GRU", "MIA", "commercial", 37000],
  ["GRU", "JFK", "commercial", 38000],
  ["GRU", "LHR", "commercial", 39000],
  ["GRU", "CDG", "commercial", 39000],
  ["GRU", "MAD", "commercial", 38000],
  ["GRU", "DXB", "commercial", 41000],
  ["EZE", "MIA", "commercial", 37000],
  ["EZE", "JFK", "commercial", 38000],
  ["EZE", "MAD", "commercial", 38000],
  ["EZE", "SCL", "commercial", 31000],
  ["SCL", "MIA", "commercial", 36000],
  ["SCL", "MAD", "commercial", 38000],
  ["LIM", "MIA", "commercial", 35000],
  ["LIM", "MAD", "commercial", 37000],
  ["BOG", "MIA", "commercial", 34000],
  ["BOG", "JFK", "commercial", 36000],
  ["BOG", "MAD", "commercial", 37000],
  ["PTY", "MIA", "commercial", 33000],
  ["PTY", "LAX", "commercial", 36000],

  // Additional popular routes
  ["MAD", "JFK", "commercial", 38000],
  ["MAD", "MIA", "commercial", 37000],
  ["MAD", "BOG", "commercial", 37000],
  ["MAD", "DXB", "commercial", 39000],
  ["BCN", "JFK", "commercial", 38000],
  ["BCN", "MIA", "commercial", 37000],
  ["BCN", "DXB", "commercial", 39000],
  ["LIS", "JFK", "commercial", 38000],
  ["LIS", "GRU", "commercial", 38000],
  ["LIS", "DXB", "commercial", 39000],
  ["DUB", "JFK", "commercial", 37000],
  ["DUB", "BOS", "commercial", 36000],
  ["DUB", "ORD", "commercial", 37000],
  ["KEF", "JFK", "commercial", 34000],
  ["KEF", "BOS", "commercial", 33000],
  ["KEF", "LHR", "commercial", 34000],
  ["ARN", "JFK", "commercial", 37000],
  ["ARN", "DXB", "commercial", 38000],
  ["OSL", "JFK", "commercial", 37000],
  ["CPH", "JFK", "commercial", 37000],
  ["CPH", "DXB", "commercial", 38000],
  ["HEL", "JFK", "commercial", 37000],
  ["HEL", "SIN", "commercial", 39000],
  ["VIE", "DXB", "commercial", 37000],
  ["VIE", "HND", "commercial", 39000],
  ["ZRH", "JFK", "commercial", 38000],
  ["ZRH", "SIN", "commercial", 39000],
  ["MUC", "JFK", "commercial", 38000],
  ["MUC", "SIN", "commercial", 39000],
  ["SVO", "DXB", "commercial", 36000],
  ["SVO", "HND", "commercial", 38000],
  ["SVO", "JFK", "commercial", 39000],
  ["LED", "DXB", "commercial", 35000],
  ["LED", "HND", "commercial", 38000],
  ["SJU", "JFK", "commercial", 33000],
  ["SJU", "MIA", "commercial", 31000],
  ["HAV", "MIA", "commercial", 30000],
  ["HAV", "MAD", "commercial", 37000],
  ["MEX", "JFK", "commercial", 35000],
  ["MEX", "LAX", "commercial", 33000],
  ["MEX", "MIA", "commercial", 32000],
  ["MEX", "MAD", "commercial", 38000],
  ["MEX", "GRU", "commercial", 37000],
];

// Generate callsigns based on route type
const CALLSIGN_PREFIXES: Record<string, string[]> = {
  military: ["RCH", "REACH", "LAGR", "CODY", "EXEC", "SAM", "VENUS", "NATO", "RRR", "ASCOT", "FAF", "GAF"],
  commercial: ["BAW", "DLH", "AFR", "KLM", "UAE", "QTR", "SIA", "JAL", "ANA", "CPA", "EVA", "THA", "KAL", "AAL", "UAL", "DAL", "BA", "LH", "AF", "EK", "QR", "SQ", "JL", "NH", "CX", "BR", "TG", "KE"],
  cargo: ["FDX", "UPS", "CAL", "DHL", "CLX"],
  surveillance: ["FORTE", "HOMER", "GORDO"],
};

export async function GET(request: Request) {
  const { searchParams } = new URL(request.url);
  const countParam = searchParams.get("count");
  const count = countParam ? parseInt(countParam, 10) : 80;
  const typeFilter = searchParams.get("type"); // "military", "commercial", "cargo", or null for all

  const time = Date.now();

  // Build active routes with animated progress
  const routes: FlightRoute[] = [];
  const usedPairs = new Set<string>();

  for (let i = 0; i < Math.min(count, ROUTE_PAIRS.length); i++) {
    const [originCode, destCode, routeType, altitude] = ROUTE_PAIRS[i];

    // Skip if type filter doesn't match
    if (typeFilter && routeType !== typeFilter) continue;

    const pairKey = `${originCode}-${destCode}`;
    if (usedPairs.has(pairKey)) continue;
    usedPairs.add(pairKey);

    const origin = LOCATIONS.find((l) => l.code === originCode);
    const dest = LOCATIONS.find((l) => l.code === destCode);
    if (!origin || !dest) continue;

    // Deterministic "random" progress based on time + index
    const progressSeed = (time / 1000 + i * 137.5) % 100;
    const progress = progressSeed / 100; // 0-1 position along route

    const prefixes = CALLSIGN_PREFIXES[routeType] || CALLSIGN_PREFIXES.commercial;
    const prefix = prefixes[i % prefixes.length];
    const flightNum = 100 + ((i * 7 + Math.floor(time / 60000)) % 900);

    routes.push({
      id: `route-${i}`,
      callsign: `${prefix}${flightNum}`,
      origin: origin.name,
      originLat: origin.lat,
      originLon: origin.lon,
      destination: dest.name,
      destLat: dest.lat,
      destLon: dest.lon,
      type: routeType,
      altitude,
      speed: routeType === "military" ? 480 : routeType === "cargo" ? 460 : 520,
      active: true,
      progress,
    });
  }

  return NextResponse.json({
    routes,
    timestamp: time,
    total: routes.length,
    byType: {
      military: routes.filter((r) => r.type === "military").length,
      commercial: routes.filter((r) => r.type === "commercial").length,
      cargo: routes.filter((r) => r.type === "cargo").length,
      surveillance: routes.filter((r) => r.type === "surveillance").length,
    },
  });
}
